// watchData.js - Comprehensive luxury watch database

export const watchProducts = [
  // ROLEX COLLECTION
  {
    id: 1,
    name: "Submariner Date",
    brand: "Rolex",
    model: "126610LN",
    price: 12550,
    originalPrice: 13200,
    image: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "diving",
    rating: 4.9,
    reviews: 847,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 3,
    description: "The ultimate diving watch with unidirectional rotating bezel and Chromalight display",
    features: ["Waterproof to 300m", "Ceramic Bezel", "Automatic Movement", "Oyster Bracelet"],
    movement: "Calibre 3235",
    caseMaterial: "Oystersteel",
    caseSize: "41mm",
    waterResistance: "300m",
    warranty: "5 years",
    madeIn: "Switzerland",
    weight: "155g",
    thickness: "12.5mm"
  },
  {
    id: 2,
    name: "Datejust 36",
    brand: "Rolex",
    model: "126234",
    price: 8950,
    originalPrice: 8950,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "dress",
    rating: 4.8,
    reviews: 1203,
    isNew: false,
    onSale: false,
    inStock: true,
    stockCount: 7,
    description: "The classic dress watch with fluted bezel and Jubilee bracelet",
    features: ["Date Display", "Fluted Bezel", "Jubilee Bracelet", "Superlative Chronometer"],
    movement: "Calibre 3235",
    caseMaterial: "Oystersteel and White Gold",
    caseSize: "36mm",
    waterResistance: "100m",
    warranty: "5 years",
    madeIn: "Switzerland",
    weight: "135g",
    thickness: "12mm"
  },
  {
    id: 3,
    name: "GMT-Master II",
    brand: "Rolex",
    model: "126710BLRO",
    price: 18750,
    originalPrice: 18750,
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "pilot",
    rating: 4.9,
    reviews: 456,
    isNew: true,
    onSale: false,
    inStock: false,
    stockCount: 0,
    description: "The traveler's watch with dual time zone display and Pepsi bezel",
    features: ["GMT Function", "Pepsi Bezel", "Oyster Bracelet", "Rapid Date Setting"],
    movement: "Calibre 3285",
    caseMaterial: "Oystersteel",
    caseSize: "40mm",
    waterResistance: "100m",
    warranty: "5 years",
    madeIn: "Switzerland",
    weight: "140g",
    thickness: "12mm"
  },

  // OMEGA COLLECTION
  {
    id: 4,
    name: "Speedmaster Professional Moonwatch",
    brand: "Omega",
    model: "310.30.42.50.01.001",
    price: 6350,
    originalPrice: 6800,
    image: "https://images.unsplash.com/photo-1509048191080-d2cc204349fd?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "chronograph",
    rating: 4.8,
    reviews: 923,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 12,
    description: "The legendary moonwatch with manual winding chronograph movement",
    features: ["Manual Winding", "Tachymeter Bezel", "Hesalite Crystal", "NASA Qualified"],
    movement: "Calibre 1861",
    caseMaterial: "Stainless Steel",
    caseSize: "42mm",
    waterResistance: "50m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "155g",
    thickness: "13mm"
  },
  {
    id: 5,
    name: "Seamaster Planet Ocean",
    brand: "Omega",
    model: "215.30.44.21.01.001",
    price: 4200,
    originalPrice: 4200,
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "diving",
    rating: 4.7,
    reviews: 567,
    isNew: true,
    onSale: false,
    inStock: true,
    stockCount: 8,
    description: "Professional diving watch with Co-Axial escapement",
    features: ["Co-Axial Escapement", "Helium Escape Valve", "Ceramic Bezel", "Anti-Magnetic"],
    movement: "Calibre 8900",
    caseMaterial: "Stainless Steel",
    caseSize: "43.5mm",
    waterResistance: "600m",
    warranty: "4 years",
    madeIn: "Switzerland",
    weight: "185g",
    thickness: "16mm"
  },

  // PATEK PHILIPPE COLLECTION
  {
    id: 6,
    name: "Calatrava",
    brand: "Patek Philippe",
    model: "5196P-001",
    price: 28500,
    originalPrice: 28500,
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "dress",
    rating: 5.0,
    reviews: 234,
    isNew: false,
    onSale: false,
    inStock: true,
    stockCount: 2,
    description: "The epitome of dress watch elegance in platinum",
    features: ["Platinum Case", "Alligator Strap", "Small Seconds", "Ultra-Thin"],
    movement: "Caliber 215 PS",
    caseMaterial: "Platinum",
    caseSize: "37mm",
    waterResistance: "30m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "65g",
    thickness: "8.1mm"
  },
  {
    id: 7,
    name: "Nautilus",
    brand: "Patek Philippe",
    model: "5711/1A-010",
    price: 45000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1580256692174-5612b8b6b33d?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "sport",
    rating: 4.9,
    reviews: 89,
    isNew: false,
    onSale: false,
    inStock: false,
    stockCount: 0,
    description: "Iconic luxury sports watch with porthole design",
    features: ["Integrated Bracelet", "Date Display", "Water Resistant", "Luxury Sports"],
    movement: "Caliber 26-330 S C",
    caseMaterial: "Stainless Steel",
    caseSize: "40mm",
    waterResistance: "120m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "155g",
    thickness: "8.3mm"
  },

  // TUDOR COLLECTION
  {
    id: 8,
    name: "Black Bay 58",
    brand: "Tudor",
    model: "M79030N-0001",
    price: 3750,
    originalPrice: 4000,
    image: "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "diving",
    rating: 4.7,
    reviews: 678,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 15,
    description: "Heritage diving watch with vintage-inspired design",
    features: ["Snowflake Hands", "Fabric Strap", "200m Water Resistant", "Vintage Design"],
    movement: "Calibre MT5402",
    caseMaterial: "Stainless Steel",
    caseSize: "39mm",
    waterResistance: "200m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "106g",
    thickness: "11.9mm"
  },
  {
    id: 9,
    name: "Pelagos 39",
    brand: "Tudor",
    model: "M25407N-0001",
    price: 4200,
    originalPrice: 4200,
    image: "https://images.unsplash.com/photo-1495856458515-0637185db551?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "diving",
    rating: 4.6,
    reviews: 345,
    isNew: true,
    onSale: false,
    inStock: true,
    stockCount: 6,
    description: "Professional diving tool watch with titanium construction",
    features: ["Titanium Case", "Self-Adjusting Bracelet", "Helium Escape Valve", "Ceramic Bezel"],
    movement: "Calibre MT5400",
    caseMaterial: "Titanium",
    caseSize: "39mm",
    waterResistance: "500m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "95g",
    thickness: "12.8mm"
  },

  // CARTIER COLLECTION
  {
    id: 10,
    name: "Tank Must",
    brand: "Cartier",
    model: "WSTA0041",
    price: 2890,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
    category: "dress",
    subcategory: "rectangular",
    rating: 4.6,
    reviews: 456,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 9,
    description: "Iconic rectangular dress watch with Roman numerals",
    features: ["Roman Numerals", "Leather Strap", "Quartz Movement", "Art Deco Design"],
    movement: "Quartz",
    caseMaterial: "Stainless Steel",
    caseSize: "31mm x 25mm",
    waterResistance: "30m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "45g",
    thickness: "6.6mm"
  },
  {
    id: 11,
    name: "Santos de Cartier",
    brand: "Cartier",
    model: "WSSA0029",
    price: 6950,
    originalPrice: 6950,
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "pilot",
    rating: 4.8,
    reviews: 289,
    isNew: true,
    onSale: false,
    inStock: true,
    stockCount: 4,
    description: "Aviation-inspired luxury watch with signature screws",
    features: ["Square Case", "Visible Screws", "QuickSwitch System", "Pilot Heritage"],
    movement: "Calibre 1847 MC",
    caseMaterial: "Stainless Steel",
    caseSize: "39.8mm",
    waterResistance: "100m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "144g",
    thickness: "9.08mm"
  },

  // JAEGER-LECOULTRE COLLECTION
  {
    id: 12,
    name: "Reverso Classic",
    brand: "Jaeger-LeCoultre",
    model: "Q2518410",
    price: 15200,
    originalPrice: 15200,
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80",
    category: "luxury",
    subcategory: "reversible",
    rating: 4.9,
    reviews: 167,
    isNew: false,
    onSale: false,
    inStock: true,
    stockCount: 3,
    description: "Art Deco masterpiece with reversible case",
    features: ["Reversible Case", "Manual Winding", "Art Deco Design", "Polo Heritage"],
    movement: "Calibre 822/2",
    caseMaterial: "Stainless Steel",
    caseSize: "26mm x 42mm",
    waterResistance: "30m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "85g",
    thickness: "7mm"
  },

  // SEIKO COLLECTION
  {
    id: 13,
    name: "Prospex Solar Diver",
    brand: "Seiko",
    model: "SNE435",
    price: 450,
    originalPrice: 500,
    image: "https://images.unsplash.com/photo-1606889464198-fcb18894cf5e?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "diving",
    rating: 4.4,
    reviews: 1234,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 25,
    description: "Solar-powered diving watch with excellent value",
    features: ["Solar Movement", "200m Water Resistant", "Unidirectional Bezel", "Luminous Hands"],
    movement: "Solar Quartz V157",
    caseMaterial: "Stainless Steel",
    caseSize: "43.5mm",
    waterResistance: "200m",
    warranty: "3 years",
    madeIn: "Japan",
    weight: "140g",
    thickness: "12mm"
  },
  {
    id: 14,
    name: "Presage Cocktail Time",
    brand: "Seiko",
    model: "SSA346",
    price: 280,
    originalPrice: 320,
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=80",
    category: "dress",
    subcategory: "automatic",
    rating: 4.3,
    reviews: 892,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 18,
    description: "Elegant dress watch with cocktail-inspired dial",
    features: ["Automatic Movement", "Power Reserve Display", "Cocktail Dial", "Hardlex Crystal"],
    movement: "4R57 Automatic",
    caseMaterial: "Stainless Steel",
    caseSize: "40.5mm",
    waterResistance: "50m",
    warranty: "2 years",
    madeIn: "Japan",
    weight: "120g",
    thickness: "12.8mm"
  },

  // CASIO COLLECTION
  {
    id: 15,
    name: "G-Shock GA-2100",
    brand: "Casio",
    model: "GA-2100-1A1",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1606800052052-a55dbc16c5e9?auto=format&fit=crop&w=800&q=80",
    category: "casual",
    subcategory: "digital",
    rating: 4.5,
    reviews: 2156,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 42,
    description: "Ultra-slim G-Shock with analog-digital display",
    features: ["Shock Resistant", "200m Water Resistant", "LED Light", "World Time"],
    movement: "Digital Quartz",
    caseMaterial: "Carbon Core Guard",
    caseSize: "45.4mm",
    waterResistance: "200m",
    warranty: "2 years",
    madeIn: "Japan",
    weight: "51g",
    thickness: "11.8mm"
  },
  {
    id: 16,
    name: "Edifice Solar Chronograph",
    brand: "Casio",
    model: "EQS-800CDB-1AV",
    price: 320,
    originalPrice: 380,
    image: "https://images.unsplash.com/photo-1594576722512-582bcd46fba3?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "chronograph",
    rating: 4.2,
    reviews: 567,
    isNew: true,
    onSale: true,
    inStock: true,
    stockCount: 14,
    description: "Solar-powered chronograph with carbon fiber bezel",
    features: ["Solar Power", "Chronograph", "Carbon Fiber Bezel", "Smartphone Link"],
    movement: "Solar Quartz",
    caseMaterial: "Stainless Steel",
    caseSize: "46.1mm",
    waterResistance: "100m",
    warranty: "1 year",
    madeIn: "Japan",
    weight: "154g",
    thickness: "12.8mm"
  },

  // TAG HEUER COLLECTION
  {
    id: 17,
    name: "Formula 1 Chronograph",
    brand: "TAG Heuer",
    model: "CAZ1010.BA0842",
    price: 1150,
    originalPrice: 1300,
    image: "https://images.unsplash.com/photo-1548068776-f1420800ddd1?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "chronograph",
    rating: 4.4,
    reviews: 445,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 11,
    description: "Racing-inspired chronograph with tachymeter bezel",
    features: ["Quartz Chronograph", "Tachymeter", "Luminous Markers", "Steel Bracelet"],
    movement: "Quartz Chronograph",
    caseMaterial: "Stainless Steel",
    caseSize: "43mm",
    waterResistance: "200m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "165g",
    thickness: "12mm"
  },

  // TISSOT COLLECTION
  {
    id: 18,
    name: "Seastar 1000 Powermatic 80",
    brand: "Tissot",
    model: "T120.407.11.041.00",
    price: 325,
    originalPrice: 375,
    image: "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "diving",
    rating: 4.3,
    reviews: 678,
    isNew: true,
    onSale: true,
    inStock: true,
    stockCount: 21,
    description: "Swiss diving watch with 80-hour power reserve",
    features: ["Powermatic 80", "Ceramic Bezel", "80-hour Power Reserve", "Swiss Made"],
    movement: "Powermatic 80.111",
    caseMaterial: "Stainless Steel",
    caseSize: "43mm",
    waterResistance: "300m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "175g",
    thickness: "12.25mm"
  },

  // CITIZEN COLLECTION
  {
    id: 19,
    name: "Promaster Diver Eco-Drive",
    brand: "Citizen",
    model: "BN0150-28E",
    price: 195,
    originalPrice: 225,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
    category: "sport",
    subcategory: "diving",
    rating: 4.5,
    reviews: 923,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 28,
    description: "Professional diving watch powered by light",
    features: ["Eco-Drive Solar", "ISO Compliant", "Polyurethane Strap", "Anti-Magnetic"],
    movement: "Eco-Drive E168",
    caseMaterial: "Stainless Steel",
    caseSize: "44mm",
    waterResistance: "200m",
    warranty: "5 years",
    madeIn: "Japan",
    weight: "95g",
    thickness: "12mm"
  },

  // HAMILTON COLLECTION
  {
    id: 20,
    name: "Khaki Field Mechanical",
    brand: "Hamilton",
    model: "H69439931",
    price: 445,
    originalPrice: 495,
    image: "https://images.unsplash.com/photo-1498550744924-34b2d07fda86?auto=format&fit=crop&w=800&q=80",
    category: "casual",
    subcategory: "field",
    rating: 4.6,
    reviews: 756,
    isNew: false,
    onSale: true,
    inStock: true,
    stockCount: 16,
    description: "Military-inspired field watch with hand-winding movement",
    features: ["Hand-Winding", "Canvas Strap", "Military Heritage", "Luminous Hands"],
    movement: "H-50 Manual",
    caseMaterial: "Stainless Steel",
    caseSize: "38mm",
    waterResistance: "50m",
    warranty: "2 years",
    madeIn: "Switzerland",
    weight: "65g",
    thickness: "9.5mm"
  }
];

// Additional data structures for filtering and organization
export const brands = [
  'Rolex', 'Omega', 'Patek Philippe', 'Tudor', 'Cartier', 
  'Jaeger-LeCoultre', 'Seiko', 'Casio', 'TAG Heuer', 
  'Tissot', 'Citizen', 'Hamilton'
];

export const categories = [
  'luxury', 'sport', 'dress', 'casual'
];

export const subcategories = [
  'diving', 'chronograph', 'dress', 'pilot', 'field', 
  'digital', 'automatic', 'rectangular', 'reversible'
];

export const priceRanges = [
  { label: 'Under $500', min: 0, max: 500 },
  { label: '$500 - $1,000', min: 500, max: 1000 },
  { label: '$1,000 - $5,000', min: 1000, max: 5000 },
  { label: '$5,000 - $15,000', min: 5000, max: 15000 },
  { label: '$15,000+', min: 15000, max: 100000 }
];

export const movements = [
  'Automatic', 'Manual', 'Quartz', 'Solar', 'Digital'
];

export const caseMaterials = [
  'Stainless Steel', 'Titanium', 'Gold', 'Platinum', 'Carbon Fiber'
];

// Featured collections
export const featuredCollections = [
  {
    id: 'dive-watches',
    name: 'Professional Diving Watches',
    description: 'Built for underwater exploration',
    products: [1, 4, 8, 9, 13, 18, 19]
  },
  {
    id: 'luxury-dress',
    name: 'Luxury Dress Watches',
    description: 'Elegance for formal occasions',
    products: [2, 6, 10, 12, 14]
  },
  {
    id: 'sports-chronograph',
    name: 'Sports Chronographs',
    description: 'Precision timing for athletes',
    products: [4, 16, 17]
  },
  {
    id: 'daily-wear',
    name: 'Everyday Timepieces',
    description: 'Perfect for daily adventures',
    products: [13, 14, 15, 18, 19, 20]
  }
];

// Blog posts related to watches (for your existing blog)
export const watchBlogPosts = [
  {
    id: 21,
    title: "The Rolex Submariner: A Deep Dive into Excellence",
    excerpt: "Exploring the history and technical mastery behind the world's most famous diving watch.",
    category: "heritage",
    author: "Marcus Rothwell",
    date: "Aug 1, 2025",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    relatedProducts: [1, 8, 9]
  },
  {
    id: 22,
    title: "Omega Speedmaster: The Moon Watch Legacy",
    excerpt: "From NASA missions to modern collections, the Speedmaster's journey through space and time.",
    category: "heritage",
    author: "Victoria Sterling",
    date: "Jul 29, 2025",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1509048191080-d2cc204349fd?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    relatedProducts: [4]
  }
];

export default watchProducts;